Add IFF_* Flags
retep998/winapi-rs pull request #565
Opened 2018-02-05 20:51 UTC by LuoZijun

IFF Flags: `IFF_UP`, `IFF_BROADCAST`, `IFF_LOOPBACK`, `IFF_POINTTOPOINT`, `IFF_MULTICAST`

2018-02-05 20:55 UTC, retep998 requested changes
These flags are used for the `iiFlags` field of `INTERFACE_INFO` which has a type of `ULONG` therefore these constants should match that type.

2018-02-05 21:04 UTC, LuoZijun commented
Updated.

2018-02-05 23:53 UTC, LuoZijun commented
What can i do for that CI error ?

2018-02-06 06:19 UTC, retep998 commented
Just update your branch against the latest upstream `0.3`.

2018-02-06 17:25 UTC, LuoZijun commented
Updated.

2018-02-09 12:00 UTC, retep998 approved these changes

2018-03-28 18:32 UTC, retep998 requested changes

2018-03-28 18:32 UTC, retep998 commented on src/shared/ws2ipdef.rs
> +pub const IFF_POINTOPOINT: ULONG = IFF_POINTTOPOINT;
As it turns out, I cannot actually find this definition in the Windows SDK. Where exactly did you find it?

This should likely be removed.

2018-07-27 11:14 UTC, closed without merging