Add um::ole2::OleInitialize, shared::wtypes::tagDVASPECT
retep998/winapi-rs pull request #651
Opened 2018-07-29 13:31 UTC by ArturKovacs

These were missing in order to implement an IDropTarget that handles file drop.

2018-07-29 13:44 UTC, retep998 requested changes

2018-07-29 13:44 UTC, retep998 commented on src/shared/wtypes.rs
> +ENUM!{enum tagDVASPECT {
This enum should be named `DVASPECT`.

2018-07-29 15:04 UTC, ArturKovacs commented
Sorry for the 'use' ordering issues. My attention is all over the place.

Is there a good way I can check these rules locally?

2018-08-06 03:52 UTC, retep998 commented
`cargo test --all-features` will run all the tests if you want to test locally.

2018-08-06 03:52 UTC, retep998 approved these changes

2018-08-06 04:49 UTC, ArturKovacs commented
Thank you next time I'll be wiser and run the tests locally before committing.

Is there anything that prevents this to be merged?

2018-09-13 18:03 UTC, ArturKovacs commented
Hello again!
I'm looking forward to seeing this merged.
If there's any reason this can't be merged in this current state I would be happy to follow your instructions.

2018-09-19 16:32 UTC, merged