Add dbt definitions
retep998/winapi-rs pull request #656
Opened 2018-08-02 12:08 UTC by trlim

2018-08-28 18:26 UTC, ncoish commented
Is this PR being considered for merging in the near future?

2018-08-29 23:25 UTC, ncoish commented on src/um/dbt.rs
> +STRUCT!{#[repr(packed)] struct DEV_BROADCAST_DEVICEINTERFACE_W {
I ran in to difficulties while this struct was #[repr(packed)] on Windows 7 while testing this. RegisterDeviceNotificationA returned a null pointer, which fluctuated between getting a 0 and a 1066 from GetLastError(). The problem was resolved by removing #[repr(packed)].

2018-09-03 15:16 UTC, trlim commented on src/um/dbt.rs
> +STRUCT!{#[repr(packed)] struct DEV_BROADCAST_DEVICEINTERFACE_W {
This is my mistake and I will remove them.
Thanks!

2018-09-19 16:59 UTC, retep998 requested changes

2018-09-19 16:59 UTC, retep998 commented on src/um/dbt.rs
> +// Copyright © 2016-2018 winapi-rs developers
This should be just 2018.

2018-09-20 14:24 UTC, retep998 approved these changes

2018-09-20 14:25 UTC, merged