Improve contributing instructions
retep998/winapi-rs pull request #694
Opened 2018-10-05 03:31 UTC by twilco

I found issue #681 in this week in Rust and decided to take a stab at it.  This PR clarifies some things that initially confused me.  Specifically:

1. Provide a link to install the Windows SDK, and how to find the headers within the SDK.  
2. I initially didn't realize I needed to run `rg "class\s+DECLSPEC_UUID.*\n?.*;" -U` on the SDK headers, not the winapi project, and was confused for a short time as to why I was only finding CONTRIBUTING.md :).  The "C version, Rust version" comments should hopefully make this more clear.

2019-10-11 03:13 UTC, Lokathor approved these changes

2020-05-12 03:02 UTC, retep998 requested changes

2020-05-12 03:02 UTC, retep998 commented on CONTRIBUTING.md
> +Make sure each field is on it's own line.
```suggestion
Make sure each field is on its own line.
```

2020-05-12 03:02 UTC, retep998 commented on CONTRIBUTING.md
> +And what our Rust binding should look like:
```suggestion
And what the Rust binding should look like:
```

2020-05-12 04:47 UTC, retep998 approved these changes

2020-05-13 21:03 UTC, merged