Add some Windows Portable Device API definitions
retep998/winapi-rs pull request #717
Opened 2018-12-07 05:42 UTC by trlim

This PR contains some definitions from WPD API headers.

2018-12-07 23:29 UTC, trlim commented
CI is failing because of missing `winapi_portabledeviceguids` library.
I couldn't figure out how to generate it yet.

2018-12-08 11:05 UTC, retep998 requested changes

2018-12-08 11:05 UTC, retep998 commented on src/um/portabledeviceapi.rs
> +    pub static CLSID_PortableDevice: CLSID;
There should never be extern statics, as their values are known and always constant and therefore can be defined as normal constants.

2019-02-14 20:54 UTC, retep998 approved these changes

2019-02-14 20:54 UTC, merged