Add Enclave API
retep998/winapi-rs pull request #731
Opened 2019-01-22 12:04 UTC by parthsane

2019-01-24 09:34 UTC, jethrogb commented on build.rs
> +    ("enclaveapi", &["basetsd", "minwinbase", "minwindef", "ntdef", "winnt"], &[]),
I think you need to add kernel32 in the last array

2019-01-24 09:34 UTC, jethrogb commented on src/um/winnt.rs
> +pub const ENCLAVE_TYPE_SGX2: DWORD = 0x00000002;
Is this correct?

2019-01-24 18:27 UTC, retep998 commented on src/um/winnt.rs
> +pub const ENCLAVE_TYPE_SGX2: DWORD = 0x00000002;
`#define ENCLAVE_TYPE_SGX2           0x00000002`

2019-01-28 09:22 UTC, parthsane commented
@retep998 , is there any thing left which is preventing the PR from going through?

2019-01-28 09:37 UTC, retep998 commented
Just a matter of me actually getting around to reviewing the PR.

2019-02-14 16:08 UTC, jethrogb commented
@retep998 Do you have any idea when you'll have time to do that?

2019-02-14 20:57 UTC, retep998 requested changes

2019-02-14 20:57 UTC, retep998 commented on src/um/enclaveapi.rs
> +
Evil blank line.

2019-02-15 07:40 UTC, jethrogb commented on src/um/enclaveapi.rs
> +
:ghost:

2019-02-15 08:20 UTC, retep998 approved these changes

2019-02-15 08:20 UTC, merged

2019-02-20 06:37 UTC, parthsane commented
@retep998 Thank you for the merge.
Do you know when we can have a release?

2019-03-05 20:10 UTC, jethrogb commented
@retep998 ping

2019-03-06 07:16 UTC, retep998 commented
I never give ETAs on release because I have no idea when I'll decide to release a new version and how long it'll take me to test for breakages and fix them before releasing. That said, I really should just have an actual schedule for when I do releases.

2019-03-06 22:07 UTC, jethrogb commented
Yeah, the last release was almost 6 months ago, I'm sure many people are waiting for features that have since been merged.