Feature/bluetooth
retep998/winapi-rs pull request #753
Opened 2019-03-19 19:20 UTC by Wodann

Extension of PR #604 that adds the ws2bth.h which is necessary for making a Windows implementation of Bluetooth sockets.

Credits to @Jarcho for all of the initial work.

2019-03-24 18:17 UTC, Wodann commented
Rebased PR to include latest commits on `0.3` branch. Can you look at this PR @retep998 ?

2019-04-17 03:44 UTC, Wodann commented
Rebased again to incorporate v0.3.7 release. The release of my crate is being blocked by this PR. @retep998 If you don't think it is possible to review this PR in the short-term, I'll just have to publish my forked version of the winapi crate. I've investigated other options, but there is unfortunately no other way..

2019-04-17 04:27 UTC, retep998 requested changes

2019-04-17 04:27 UTC, retep998 commented on src/shared/bthdef.rs
> +// Copyright © 2018 winapi-rs developers
The copyright lines were removed from `winapi` recently and should be removed from this PR.

2019-04-17 04:27 UTC, retep998 commented on src/shared/bthdef.rs
> +    SDP_PROTOCOL_UUID16}
All these `DEFINE_BLUETOOTH_UUID128!` invocations should be single line invocations.

2019-04-17 04:27 UTC, retep998 commented on src/shared/bthdef.rs
> +    IoCaps_Undefined       = 0xff,
No aligned indentation.

2019-04-17 04:27 UTC, retep998 commented on src/um/bluetoothapis.rs
> +    CHAR, HANDLE, LONG, LONGLONG, LPCWSTR, LPWSTR, PVOID, PWSTR, SHORT, ULONGLONG, WCHAR
Trailing comma is missing.

2019-04-17 04:27 UTC, retep998 commented on src/um/bluetoothapis.rs
> +    BLUETOOTH_AUTHENTICATION_METHOD_LEGACY     = 0x1,
Extra spaces that shouldn't be there.

2019-04-17 04:27 UTC, retep998 commented on src/um/bluetoothapis.rs
> +    BLUETOOTH_IO_CAPABILITY_UNDEFINED       = 0xff,
No aligned indentation.

2019-04-17 04:27 UTC, retep998 commented on src/um/bluetoothapis.rs
> +    BLUETOOTH_MITM_ProtectionNotDefined            = 0xff,
What even.

2019-04-17 04:27 UTC, retep998 commented on src/um/bluetoothleapis.rs
> +    PFNBLUETOOTH_GATT_EVENT_CALLBACK
Missing trailing comma.

2019-04-17 04:27 UTC, retep998 commented on src/um/bthledef.rs
> +pub const BTHLEENUM_ATT_MTU_MAX: USHORT = u16::MAX;
The value of this should be `MAX_USHORT` but since that is apparently never defined anywhere, this should just be commented out.

2019-04-17 04:27 UTC, retep998 commented on src/um/ws2bth.rs
> +    BTH_ADDR, MAX_L2CAP_INFO_DATA_LENGTH, MAX_L2CAP_PING_DATA_LENGTH, MAX_UUIDS_IN_QUERY
Trailing comma.

2019-04-17 04:27 UTC, retep998 commented on src/um/ws2bth.rs
> +    port: ULONG,            // RFCOMM channel or L2CAP PSM
Remove these comments.

2019-04-17 04:27 UTC, retep998 commented on src/um/ws2bth.rs
> +pub const BT_ADDR_STRING_SIZE: DWORD = 12; // max size from WSAAddressToString
This is actually `BTH_ADDR_STRING_SIZE`. Also remove the comment.

2019-04-17 04:27 UTC, retep998 commented on src/um/ws2bth.rs
> +pub const RFCOMM_MIN_MTU: ULONG = 0x00000017;  // RFCOMM spec sec 5.3 table 5.1
Just remove all these extraneous comments please.

2019-04-17 05:58 UTC, Wodann commented
Thank you for your review @retep998. I fixed all of the issues you pointed out, and did the same in places where I found similar issues. I hope the updated PR is up to your standards.

I also rebased on the PR on top of your latest commit in the `0.3` branch again to prevent potential merge conflicts.

2019-06-03 15:12 UTC, retep998 approved these changes

2019-06-03 15:12 UTC, merged