Update audioclient & add audiopolicy
retep998/winapi-rs pull request #796
Opened 2019-08-08 21:17 UTC by trmcnvn

This PR updates `um::audioclient` to add missing elements and adds a new `um::audiopolicy` feature.

Closes an older PR #645

2019-08-28 05:43 UTC, retep998 commented
PR needs to be rebased due to failing CI.

2020-05-12 11:12 UTC, retep998 requested changes

2020-05-12 11:12 UTC, retep998 commented on src/um/audioclient.rs
> +pub const AUDCLNT_S_NO_SINGLE_PROCESS: SCODE = AUDCLNT_SUCCESS!(0x00d);
Where is this constant coming from? I can't find it in version 10.0.18362.0 of the Windows SDK.

2020-05-12 11:12 UTC, retep998 commented on src/um/audioclient.rs
> +    AMBISONICS_NORMALIZATION_N3D = 0x1,
```suggestion
    AMBISONICS_NORMALIZATION_N3D,
```

2020-05-12 11:12 UTC, retep998 commented on src/um/audiopolicy.rs
> +  DisconnectReasonExclusiveModeOverride = 0x5,
```suggestion
  DisconnectReasonServerShutdown,
  DisconnectReasonFormatChanged,
  DisconnectReasonSessionLogoff,
  DisconnectReasonSessionDisconnected,
  DisconnectReasonExclusiveModeOverride,
```

2020-05-12 11:12 UTC, retep998 commented on src/um/audiopolicy.rs
> +    NewMute: BOOL,
```suggestion
    NewMute: BOOL,
    EventContext: LPCGUID,
```

2020-05-13 21:06 UTC, trmcnvn commented on src/um/audioclient.rs
> +pub const AUDCLNT_S_NO_SINGLE_PROCESS: SCODE = AUDCLNT_SUCCESS!(0x00d);
https://docs.microsoft.com/en-us/windows/win32/api/audiopolicy/nf-audiopolicy-iaudiosessioncontrol2-getprocessid

```
The session spans more than one process. In this case, pRetVal receives the initial identifier of the process that created the session. To use this value , include the following definition:

#define AUDCLNT_S_NO_SINGLE_PROCESS AUDCLNT_SUCCESS (0x00d)
```

2020-05-13 21:06 UTC, trmcnvn commented
I'm going to close this PR as #876 supersedes this one. The latest review comments should most likely be addressed there if they haven't already. /cc @JoshuaBatty

2020-05-13 21:06 UTC, closed without merging