Add fltlib API
retep998/winapi-rs pull request #923
Opened 2020-07-13 18:12 UTC by MathGas

this PR adds support for fltlib API :
  - https://docs.microsoft.com/en-us/windows/win32/api/fltuser/ 
  - https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/filter-manager-concepts

This way, winapi is (normally) able to load/unload, connect to a minifilter..

2020-11-27 23:06 UTC, roblabla requested changes
Requires changes.

- Organization of code
  - All definitions go into the source file that directly maps to the header the definition is from:
    - :warning: some definitions in fltuser should go in a separate `shared::fltuserstructures` module.
  - Definitions are defined in the same order as they are in the original header
    - :warning: Definitions are not given in the same order as the original header.

- Extern functions
  - ABIS are correct (WINAPI = "system"): :heavy_check_mark: 
  - Names are correct (functions, parameters): :heavy_check_mark: 
  - Parameter types are correct: :warning: PHANDLE used instead of *mut HANDLE (resolves to the same underlying type).
  - Return types are correct: :heavy_check_mark: 

- Constants
  - Names are correct: :heavy_check_mark: 
  - Values are correct: :heavy_check_mark: 
  - Types are correct: :heavy_check_mark: 
    - All the ULONG consts go in various ULONG members of structures.
    - `FLT_PORT_FLAG_SYNC_HANDLE` is used with `FilterConnectCommunicationPort`' dwOptions, a DWORD.

- Structs
  - Struct definitions are wrapped in `STRUCT!` macro: :heavy_check_mark: 
  - Struct names are correct: :warning: problems around anonymous names
  - Param names are correct: :heavy_check_mark: 
  - Param types are correct: :heavy_check_mark: 

- Unions
  - Unions are wrapped in the `UNION!` macro: :heavy_check_mark: 
  - Union names are correct: :warning: problems around anonymous unions 
  - Union container size is correct: :heavy_check_mark: 
  - Union member names are correct: :heavy_check_mark: 
  - Union member mutable accessor is in form `FieldName_mut`: :warning: 
  - Union member types are correct: :heavy_check_mark: 

- Enums
  - Enum definitions are wrapped in `ENUM!` macro: :heavy_check_mark: 
  - Enum names are correct: :heavy_check_mark: 
  - Enum variant names are correct: :heavy_check_mark: 
  - Enum variant values are correct: :heavy_check_mark:

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    // FilterVolumeClose@4 // ?????
```suggestion
```

Not sure what this comment is about? I couldn't find FilterVolumeClose in the header.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +pub type HFILTER = HANDLE;
A lot of those definitions should go in a module `shared::fltuserstructures`, as they are defined in a header called `shared/fltuserstructures.h`

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +pub type PHFILTER = *mut HFILTER;
```suggestion
```

I couldn't find `PHFILTER` in the windows header files.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +pub type PHFILTER_INSTANCE = *mut HFILTER_INSTANCE;
```suggestion
```

I couldn't find `PHFILTER_INSTANCE` in the windows header files.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    FilterFullInformation = 0,
```suggestion
    FilterFullInformation,
```

Windows header file doesn't specify `= 0`.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    FilterVolumeBasicInformation = 0,
```suggestion
    FilterVolumeBasicInformation,
```

Windows header file doesn't specify = 0.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    InstanceBasicInformation = 0,
```suggestion
    InstanceBasicInformation,
```

Windows header file doesn't specify `= 0`.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +UNION!{union FILTER_AGGREGATE_BASIC_INFORMATION_Type_u {
```suggestion
UNION!{union FILTER_AGGREGATE_BASIC_INFORMATION_Type {
```

From the contributor guide, on handling anonymous structs/unions:

> If the field does have a name, such as Bar, but still contains an anonymous struct or union then retain the name of Bar for the field and name the anonymous struct or union after the field, such as FOO_Bar.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +STRUCT!{struct FILTER_AGGREGATE_BASIC_INFORMATION_u_s_MiniFilter {
```suggestion
STRUCT!{struct FILTER_AGGREGATE_BASIC_INFORMATION_Type_MiniFilter {
```

From the contributor guide, on handling anonymous structs/unions:

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +STRUCT!{struct FILTER_AGGREGATE_BASIC_INFORMATION_u_s_LegacyFilter {
```suggestion
STRUCT!{struct FILTER_AGGREGATE_BASIC_INFORMATION_Type_LegacyFilter {
```

From the contributor guide, on handling anonymous structs/unions:

> If the field does have a name, such as Bar, but still contains an anonymous struct or union then retain the name of Bar for the field and name the anonymous struct or union after the field, such as FOO_Bar.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    MiniFilter mut_MiniFilter: FILTER_AGGREGATE_BASIC_INFORMATION_u_s_MiniFilter,
```suggestion
    MiniFilter MiniFilter_mut: FILTER_AGGREGATE_BASIC_INFORMATION_Type_MiniFilter,
```

The name of the mutable accessor should be `FieldName_mut` with a `_mut` suffix.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    LegacyFilter mut_LegacyFilter: FILTER_AGGREGATE_BASIC_INFORMATION_u_s_LegacyFilter,
```suggestion
    LegacyFilter LegacyFilter_mut: FILTER_AGGREGATE_BASIC_INFORMATION_Type_LegacyFilter,
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    Type: FILTER_AGGREGATE_BASIC_INFORMATION_Type_u,
```suggestion
    Type: FILTER_AGGREGATE_BASIC_INFORMATION_Type,
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +STRUCT!{struct FILTER_AGGREGATE_STANDARD_INFORMATION_u_s_MiniFilter {
```suggestion
STRUCT!{struct FILTER_AGGREGATE_STANDARD_INFORMATION_Type_MiniFilter {
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +STRUCT!{struct FILTER_AGGREGATE_STANDARD_INFORMATION_u_s_LegacyFilter {
```suggestion
STRUCT!{struct FILTER_AGGREGATE_STANDARD_INFORMATION_Type_LegacyFilter {
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +UNION!{union FILTER_AGGREGATE_STANDARD_INFORMATION_Type_u {
```suggestion
UNION!{union FILTER_AGGREGATE_STANDARD_INFORMATION_Type {
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> + }}
```suggestion
}}
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> + STRUCT!{struct FILTER_VOLUME_STANDARD_INFORMATION {
```suggestion
STRUCT!{struct FILTER_VOLUME_STANDARD_INFORMATION {
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> + }}
```suggestion
}}
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    Type: FILTER_AGGREGATE_STANDARD_INFORMATION_Type_u,
```suggestion
    Type: FILTER_AGGREGATE_STANDARD_INFORMATION_Type,
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    MiniFilter mut_MiniFilter: FILTER_AGGREGATE_STANDARD_INFORMATION_u_s_MiniFilter,
```suggestion
    MiniFilter MiniFilter_mut: FILTER_AGGREGATE_STANDARD_INFORMATION_Type_MiniFilter,
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    LegacyFilter mut_LegacyFilter: FILTER_AGGREGATE_STANDARD_INFORMATION_u_s_LegacyFilter,
```suggestion
    LegacyFilter LegacyFilter_mut: FILTER_AGGREGATE_STANDARD_INFORMATION_Type_LegacyFilter,
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +STRUCT!{struct INSTANCE_AGGREGATE_STANDARD_INFORMATION_u_s_LegacyFilter {
```suggestion
STRUCT!{struct INSTANCE_AGGREGATE_STANDARD_INFORMATION_Type_LegacyFilter {
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +UNION!{union INSTANCE_AGGREGATE_STANDARD_INFORMATION_Type_u {
```suggestion
UNION!{union INSTANCE_AGGREGATE_STANDARD_INFORMATION_Type {
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +STRUCT!{struct INSTANCE_AGGREGATE_STANDARD_INFORMATION_u_s_MiniFilter {
```suggestion
STRUCT!{struct INSTANCE_AGGREGATE_STANDARD_INFORMATION_Type_MiniFilter {
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    MiniFilter mut_MiniFilter: INSTANCE_AGGREGATE_STANDARD_INFORMATION_u_s_MiniFilter,
```suggestion
    MiniFilter MiniFilter_mut: INSTANCE_AGGREGATE_STANDARD_INFORMATION_Type_MiniFilter,
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    LegacyFilter mut_LegacyFilter: INSTANCE_AGGREGATE_STANDARD_INFORMATION_u_s_LegacyFilter,
```suggestion
    LegacyFilter LegacyFilter_mut: INSTANCE_AGGREGATE_STANDARD_INFORMATION_Type_LegacyFilter,
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +    Type: INSTANCE_AGGREGATE_STANDARD_INFORMATION_Type_u,
```suggestion
    Type: INSTANCE_AGGREGATE_STANDARD_INFORMATION_Type,
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +        hPort: PHANDLE
```suggestion
        hPort: *mut HANDLE
```

The windows header file uses a raw pointer here.

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +        hFilter: PHFILTER
```suggestion
        hFilter: *mut HFILTER
```

2020-11-27 23:06 UTC, roblabla commented on src/um/fltuser.rs
> +        hInstance: PHFILTER_INSTANCE
```suggestion
        hInstance: *mut HFILTER_INSTANCE
```

2020-11-30 14:40 UTC, roblabla approved these changes
LGTM :+1:

All problems from previous review fixed!

2021-01-09 19:16 UTC, mvforell commented
Any estimate on when this will be merged and when a new version will be published?

2022-07-22 10:52 UTC, closed without merging